### PR TITLE
Lineage-ify

### PR DESCRIPTION
**Pull request by Haxk20**
This includes some basic LineageOS changes. More device specific changes will follow up tomorrow.
In my original tree i did not have setup-makefiles. I did it more hacky way. But i adopted the setup-makefiles one.

### CODE REVIEW

**Comment by Haxk20** [comment]
Interesting. The commit that adds the battery led and that isnt working. TBH i didnt test it until i posted it since i was sure it would work but it doesnt.

**Comment by ix5** [comment]
You don't really need the setup-makesfiles script, it's for devices that kang blobs from stock and we don't do that crap on SODP.

**Comment by Haxk20** [comment]
TBH with you after learning that the second camera wont even work on AOSP because vendor blobs dont have the support i would rather kang the blobs from stock and make tons of shims to get the second camera working. But as this is supposed to be from SODP i will drop the setup-makefiles.

**Review by ix5 — COMMENTED** [review]
`notificatio` -> `notification`

Also, it's customary to keep git commit descriptions under 60 characters in line length.

**Comment by ix5** [comment]
Please squash the commits so that you end up with two commits:
- "Lineage-ify"
- "Add config for battery & notification LED"

**Comment by Haxk20** [comment]
@ix5 This will do as the config for battery LED didnt work yet. Have to look into more.

**Comment by Haxk20** [comment]
@ix5 its ready to be merged now.

**Comment by Haxk20** [comment]
@ix5 @MarijnS95 can some of you merge it as i dont have the permissions to do so.
When merging this merge also kirin and mermaid changes as this is useless without them.

**Comment by ix5** [comment]
@Haxk20 I've given you write permissions, you can merge the rest yourself.

If you want to have a chat, please join <strike>redacted</strike> and announce yourself as "Haxk20 from github".

**Comment by Haxk20** [comment]
@ix5 I did join and annouced myself as Haxk20 from github HAHA. And thanks

**Comment by MarijnS95** [comment]
So, no dualsim devices on afstamming? :disappointed:

**Comment by Haxk20** [comment]
@MarijnS95 I will add back the dual sim support when i get to it. But i think the better way would be to have a flashable zip that turns the ROM into dual sim as LineageOS devs do it for a long time now.

**Comment by MarijnS95** [comment]
Luckily we are not following LOS policy :man_facepalming: 

When I compile for DSDS mermaid I'd like it to just work, flashing a zip makes quick iteration horrible.

**Comment by Haxk20** [comment]
@MarijnS95 Yeah indeed.
As i said will look into it when i get the time. Now i have to fix phone due to the recovery bug i reported on sony github. You might actually know whats up with it.
[issue](https://github.com/sonyxperiadev/bug_tracker/issues/471)

**Pull request merged**
